---
# TODO remove it only for molecule
- name: Создать директорию /usr/share/man/man1 (если отсутствует)
  file:
    path: /usr/share/man/man1
    state: directory
    mode: '0755'
  become: yes

- name: Install java17
  ansible.builtin.apt:
    name: openjdk-17-jre-headless
    state: present
    update_cache: yes

- name: Create kafkaui user and group
  import_tasks: user.yml

- name: Create a directory /usr/local/lib/kafka-ui
  ansible.builtin.file:
    path: /usr/local/lib/kafka-ui
    state: directory
    mode: '0750'
    owner: '{{ kafka_ui_user }}'
    group: '{{ kafka_ui_user }}'

- name: Download kafka-ui-api JAR
  get_url:
    url: "https://github.com/provectus/kafka-ui/releases/download/v0.7.2/kafka-ui-api-v0.7.2.jar"
    dest: "/usr/local/lib/kafka-ui/kafka-ui-api-v0.7.2.jar"
    owner: '{{ kafka_ui_user }}'
    group: '{{ kafka_ui_user }}'
    mode: '0644'

- name: Create a directory /etc/kafka-ui
  ansible.builtin.file:
    path: /etc/kafka-ui
    state: directory
    owner: '{{ kafka_ui_user }}'
    group: '{{ kafka_ui_user }}'
    mode: '0755'

- name: Create a directory /etc/kafkaui
  ansible.builtin.file:
    path: /etc/kafkaui
    state: directory
    owner: '{{ kafka_ui_user }}'
    group: '{{ kafka_ui_user }}'
    mode: '0755'

- name: Deploy Kafka UI configuration file
  template:
    src: application.yaml.j2
    dest: /etc/kafka-ui/application.yaml
    owner: '{{ kafka_ui_user }}'
    group: '{{ kafka_ui_user }}'
    mode: '0755'
  notify: restart kafka ui

- name: Deploy systemd unit file
  template:
    src: kafka-ui.service.j2
    dest: /etc/systemd/system/kafka-ui.service
  notify: restart kafka ui
    
- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start kafka ui
  ansible.builtin.systemd_service:
    name: kafka-ui.service
    state: started
    enabled: true