---
- name: Prepare linux host
  import_tasks: prepare.yml

- name: Configure
  import_tasks: configure.yml

- name: start kafka ui
  ansible.builtin.systemd_service:
    name: kafka-ui.service
    state: started
    enabled: true

- name: Check Health of kafka-ui
  ansible.builtin.uri:
    url: "http://localhost:{{ kafka_ui.server_port }}"