dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../"

verifier:
  name: ansible
  